version: "3"
services:
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    expose:
    - 3306
    tty: true
